# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hi. I'm Donald.
tagline:          'I do data science.'
description:      'I do data science. <br/>  <a href="https://twitter.com/physicsbliss?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-size="large" data-show-screen-name="false" data-show-count="false">Follow @physicsbliss</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>'
baseurl:          https://dleebrown.github.io/

author:
  name:           'Donald Lee-Brown'
  url:            https://twitter.com/physicsbliss

paginate:         5

# Custom vars
version:          2.1.0

github: 
  repo:           https://github.com/poole/hyde
