# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hi. I'm Donald.
tagline:          'I do data science.'
description:      'I do data science. <br /> <div class="socializer a sr-48px sr-squircle sr-opacity sr-icon-white sr-pad"><span class="sr-github"><a href="https://github.com/dleebrown" target="_blank" title="Github"><i class="fa fa-github"></i></a></span><span class="sr-twitter"><a href="https://twitter.com/physicsbliss" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></span><span class="sr-linkedin"><a href="https://www.linkedin.com/in/donaldbleebrown" target="_blank" title="LinkedIn"><i class="fa fa-linkedin"></i></a></span></div>'
baseurl:          https://dleebrown.github.io/

author:
  name:           'Donald Lee-Brown'
  url:            https://twitter.com/physicsbliss

paginate:         5

# Custom vars
version:          2.1.0

github: 
  repo:           https://github.com/dleebrown
