# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hi. I'm Donald
tagline:          'Not that Donald. The other one.'
description:      'I do data science. <a href="https://twitter.com/physicsbliss" target="_blank">@PhysicsBliss</a>.'
baseurl:          https://dleebrown.github.io/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
