# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hi. I'm Donald.
tagline:          'I do data science.'
description:      'I do data science. <br/>  <a href="https://twitter.com/physicsbliss" target="_blank">@PhysicsBliss</a> <script src="//platform.linkedin.com/in.js" type="text/javascript"></script>
<script type="IN/MemberProfile" data-id="https://www.linkedin.com/in/donaldbleebrown" data-format="click" data-related="false"></script>'
baseurl:          https://dleebrown.github.io/

author:
  name:           'Donald Lee-Brown'
  url:            https://twitter.com/physicsbliss

paginate:         5

# Custom vars
version:          2.1.0

github: 
  repo:           https://github.com/poole/hyde
