# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hi. I'm Donald.
tagline:          'I do data science.'
description:      'I do data science.  <a href="https://twitter.com/physicsbliss" target="_blank">@PhysicsBliss</a>'
baseurl:          https://dleebrown.github.io/

author:
  name:           'Donald Lee-Brown'
  url:            https://twitter.com/physicsbliss

paginate:         5

# Custom vars
version:          2.1.0

github:           https://github.com/dleebrown
  repo:           https://github.com/poole/hyde
