# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hi. I'm Donald
tagline:          'The other Donald. The one that does data science.'
description:      'This is where I put things I want the world to see, even if the world doesn't want to see them.'
baseurl:          https://dleebrown.github.io/

author:
  name:           'Donald Lee-Brown'
  url:            https://twitter.com/physicsbliss

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dleebrown/dleebrown.github.io
