# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hi! I'm Donald. 
tagline:          'The other Donald. The data scientist one.'
description:      'This is my personal page, where I put things I want the world to see, even if the world doesn't want to see them.'
baseurl:          http://dleebrown.github.io/

author:
  name:           'Donald lee-Brown'
  url:            http://dleebrown.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dleebrown/dleebrown.github.io
